name: Page tests
on:
  push:
    paths:
      - 'src/pages/**'
      - 'src/pages-chibi/**'
  pull_request:
    paths:
      - 'src/pages/**'
      - 'src/pages-chibi/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
    - id: files
      continue-on-error: true
      uses: jitterbit/get-changed-files@b17fbb00bdc0c0f63fcf166580804b4d2cdc2a42 # v1
      with:
        format: 'json'
    - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
      with:
        node-version: '22.x'
    - name: Checkout test data
      uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      with:
        repository: MALSync/test_data
        ref: 'master'
        path: test/dist/headless
    - name: Decode
      run: node decrypt.js
      working-directory: test/dist/headless
    # see https://github.com/puppeteer/puppeteer/issues/12818
    - name: Disable AppArmor
      run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns
    - name: Page Tests
      run: |
        npm ci
        npm run build:webextension
        npm run test:headless
      env:
        CI: true
        FILES: ${{steps.files.outputs.added_modified}}

